version: '3'

services:
  web:
    build: ./php-task-demo
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
    volumes:
      - ./php-task-demo/init.sql:/docker-entrypoint-initdb.d/init.sql
